name: Test my typescript action

on:
  pull_request:
    paths:
      - 'src/**'
      - 'dist/**'
      - tsconfig.json
      - package*

env:
  IMAGE_NAME: alpine:3.10.1

jobs:
  jest:
    name: Test with jest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Jest
        run: npm run test

  test1:
    name: Test for with parameter
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install

    # - name: Test
    #   run: npm run test

    - name: Build
      run: npm run build

    - name: Pull docker image
      run: docker pull alpine:3.10.3

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        image: alpine:3.10.1
        issue_label: trivy,vulnerability,test
        issue_title: Security Alert Test
        issue_assignee: homoluctus

    - uses: homoluctus/slatify@v1.9.0
      if: always()
      with:
        type: ${{ job.status }}
        job_name: ':ts: *test gitrivy*'
        channel: '#develop'
        url: ${{ secrets.SLACK_WEBHOOK }}

  test2:
    name: Test for getting image name from enviroment variable
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Pull docker image
        run: docker pull alpine:3.10.3

      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_label: trivy,vulnerability,test
          issue_title: Security Alert Test
          issue_assignee: homoluctus

      - uses: homoluctus/slatify@v1.9.0
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':ts: *test gitrivy*'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
